import type { BuildDevice } from './types';

export const buildLabDevices: BuildDevice[] = [
  {
    id: 'macbook-air-m3',
    name: 'ByteBook Air M3',
    slug: 'bytebook-air-m3',
    category: 'LAPTOP',
    brand: 'ByteBook',
    price: 999900,
    image: '/build-lab/bytebook-air-m3.svg',
    summary: 'MacBook-class developer laptop with Thunderbolt and Apple Silicon efficiency.',
    capabilities: {
      ports: ['THUNDERBOLT_4', 'USB_C'],
      operatingSystems: ['macOS'],
      powerInputW: 67,
      outputs: ['THUNDERBOLT_4'],
      dimensionsMm: { width: 304, depth: 212, height: 16 },
      workloadTags: ['coding', 'design', 'mobile-dev'],
      upgradeabilityTags: ['external-storage', 'dock'],
      compatibilityTags: ['apple-silicon', 'portable'],
    },
    tags: ['portable', 'macOS', 'thunderbolt'],
    scoreWeight: 92,
    recommendedFor: ['Coding', 'Design', 'Travel'],
  },
  {
    id: 'bytebook-pro-x',
    name: 'ByteBook Pro X',
    slug: 'bytebook-pro-x',
    category: 'LAPTOP',
    brand: 'ByteBook',
    price: 1499900,
    image: '/build-lab/bytebook-pro-x.svg',
    summary: 'Windows developer laptop with discrete graphics and higher power ceiling.',
    capabilities: {
      ports: ['THUNDERBOLT_4', 'USB_C', 'HDMI'],
      operatingSystems: ['Windows', 'Linux'],
      powerInputW: 140,
      outputs: ['HDMI', 'THUNDERBOLT_4'],
      dimensionsMm: { width: 358, depth: 245, height: 22 },
      workloadTags: ['backend', 'ml', 'gaming', 'builds'],
      upgradeabilityTags: ['external-gpu', 'dock', 'storage'],
      compatibilityTags: ['creator', 'high-power'],
    },
    tags: ['Windows', 'graphics', 'performance'],
    scoreWeight: 95,
    recommendedFor: ['Builds', 'Games', 'ML'],
  },
  {
    id: 'byteworkstation-z7',
    name: 'ByteWorkstation Z7',
    slug: 'byteworkstation-z7',
    category: 'DESKTOP',
    brand: 'ByteWork',
    price: 1899900,
    image: '/build-lab/byteworkstation-z7.svg',
    summary: 'Upgradeable desktop/workstation tower for heavy compile and render loads.',
    capabilities: {
      ports: ['USB_C', 'USB_A', 'HDMI', 'DISPLAYPORT', 'ETHERNET'],
      operatingSystems: ['Windows', 'Linux'],
      powerInputW: 750,
      outputs: ['DISPLAYPORT', 'HDMI'],
      dimensionsMm: { width: 210, depth: 420, height: 450 },
      workloadTags: ['compile', 'render', 'virtualization'],
      upgradeabilityTags: ['gpu', 'storage', 'memory'],
      compatibilityTags: ['tower', 'modular'],
    },
    tags: ['workstation', 'upgradeable', 'desktop'],
    scoreWeight: 98,
    recommendedFor: ['Compiling', 'Rendering', 'Virtualization'],
  },
  {
    id: 'byteview-34',
    name: 'ByteView 34 UltraWide',
    slug: 'byteview-34-ultrawide',
    category: 'MONITOR',
    brand: 'ByteView',
    price: 399999,
    image: '/build-lab/byteview-34-ultrawide.svg',
    summary: '34-inch ultrawide monitor for multi-window productivity.',
    capabilities: {
      inputs: ['HDMI', 'DISPLAYPORT', 'USB_C'],
      maxDisplayResolution: '3440x1440',
      maxRefreshHz: 144,
      bandwidthGbps: 32,
      dimensionsMm: { width: 815, depth: 250, height: 520 },
      compatibilityTags: ['ultrawide', 'high-refresh'],
      workloadTags: ['coding', 'video-editing'],
    },
    tags: ['display', 'ultrawide', 'high-refresh'],
    scoreWeight: 94,
    recommendedFor: ['Coding', 'Timeline work', 'Split view'],
  },
  {
    id: 'byteview-27-pro',
    name: 'ByteView 27 Pro',
    slug: 'byteview-27-pro',
    category: 'MONITOR',
    brand: 'ByteView',
    price: 239999,
    image: '/build-lab/byteview-27-pro.svg',
    summary: '27-inch 4K display with wide compatibility and accurate color.',
    capabilities: {
      inputs: ['HDMI', 'DISPLAYPORT', 'USB_C'],
      maxDisplayResolution: '3840x2160',
      maxRefreshHz: 60,
      bandwidthGbps: 18,
      dimensionsMm: { width: 610, depth: 220, height: 460 },
      compatibilityTags: ['4k', 'creator'],
      workloadTags: ['design', 'analysis'],
    },
    tags: ['display', '4k', 'creator'],
    scoreWeight: 88,
    recommendedFor: ['Design', 'Analysis', 'Office'],
  },
  {
    id: 'bytedock-12',
    name: 'ByteDock 12-in-1',
    slug: 'bytedock-12-in-1',
    category: 'DOCK',
    brand: 'ByteDock',
    price: 14999,
    image: '/featured-products/bytedock-12-in-1.svg',
    summary: 'USB-C dock with display out, ethernet, card reader, and charging.',
    capabilities: {
      ports: ['USB_C', 'USB_A', 'HDMI', 'DISPLAYPORT', 'ETHERNET'],
      powerInputW: 100,
      powerOutputW: 85,
      bandwidthGbps: 40,
      dimensionsMm: { width: 120, depth: 70, height: 25 },
      compatibilityTags: ['dock', 'pd', 'multiport'],
      workloadTags: ['laptop-expansion'],
    },
    tags: ['dock', 'usb-c', 'pd'],
    scoreWeight: 90,
    recommendedFor: ['Single cable desk', 'Travel workstation'],
  },
  {
    id: 'bytedock-lite',
    name: 'ByteDock Lite',
    slug: 'bytedock-lite',
    category: 'DOCK',
    brand: 'ByteDock',
    price: 7999,
    image: '/featured-products/bytedock-12-in-1.svg',
    summary: 'Compact USB-C hub with basic display and data passthrough.',
    capabilities: {
      ports: ['USB_C', 'USB_A', 'HDMI'],
      powerInputW: 60,
      powerOutputW: 45,
      bandwidthGbps: 10,
      dimensionsMm: { width: 95, depth: 55, height: 20 },
      compatibilityTags: ['hub', 'portable'],
    },
    tags: ['hub', 'portable', 'budget'],
    scoreWeight: 72,
    recommendedFor: ['Travel', 'Secondary desk'],
  },
  {
    id: 'bytekeys-pro-75',
    name: 'ByteKeys Pro 75',
    slug: 'bytekeys-pro-75',
    category: 'KEYBOARD',
    brand: 'ByteKeys',
    price: 12999,
    image: '/build-lab/bytekeys-pro-75.svg',
    summary: 'Compact mechanical keyboard with hot-swap support and programmable layers.',
    capabilities: {
      ports: ['USB_C'],
      operatingSystems: ['macOS', 'Windows', 'Linux'],
      compatibilityTags: ['input', 'mechanical', 'hot-swap'],
      workloadTags: ['typing', 'coding'],
      dimensionsMm: { width: 320, depth: 135, height: 35 },
    },
    tags: ['keyboard', 'mechanical', '75%'],
    scoreWeight: 84,
    recommendedFor: ['Typing', 'Coding'],
  },
  {
    id: 'bytemouse-ergo-x',
    name: 'ByteMouse Ergo X',
    slug: 'bytemouse-ergo-x',
    category: 'MOUSE',
    brand: 'ByteMouse',
    price: 8999,
    image: '/build-lab/bytemouse-ergo-x.svg',
    summary: 'Ergonomic mouse with silent clicks and programmable buttons.',
    capabilities: {
      ports: ['USB_C', 'USB_A'],
      operatingSystems: ['macOS', 'Windows', 'Linux'],
      compatibilityTags: ['input', 'ergonomic'],
      workloadTags: ['precision', 'scrolling'],
      dimensionsMm: { width: 115, depth: 70, height: 45 },
    },
    tags: ['mouse', 'ergonomic', 'silent'],
    scoreWeight: 79,
    recommendedFor: ['Precision work', 'Comfort'],
  },
  {
    id: 'bytedrive-nvme-2tb',
    name: 'ByteDrive NVMe 2TB',
    slug: 'bytedrive-nvme-2tb',
    category: 'STORAGE',
    brand: 'ByteDrive',
    price: 17999,
    image: '/build-lab/bytedrive-nvme-2tb.svg',
    summary: 'Portable NVMe storage for projects, media, and backups.',
    capabilities: {
      ports: ['USB_C'],
      storageInterfaces: ['NVME', 'USB 3.2'],
      bandwidthGbps: 10,
      compatibilityTags: ['storage', 'portable'],
      workloadTags: ['backups', 'media'],
      dimensionsMm: { width: 110, depth: 55, height: 12 },
    },
    tags: ['storage', 'nvme', 'portable'],
    scoreWeight: 76,
    recommendedFor: ['Backups', 'Media cache'],
  },
  {
    id: 'bytegpu-core-4090',
    name: 'ByteGPU Core 4090',
    slug: 'bytegpu-core-4090',
    category: 'GPU',
    brand: 'ByteGPU',
    price: 2399900,
    image: '/build-lab/bytegpu-core-4090.svg',
    summary: 'High-performance desktop GPU for rendering and CUDA workloads.',
    capabilities: {
      ports: ['PCIe'],
      powerInputW: 450,
      compatibilityTags: ['gpu', 'desktop-only'],
      workloadTags: ['render', 'ml', 'gaming'],
      upgradeabilityTags: ['pcie-slot', 'high-wattage'],
      dimensionsMm: { width: 336, depth: 142, height: 58 },
    },
    tags: ['gpu', 'desktop', 'high-power'],
    scoreWeight: 97,
    recommendedFor: ['Rendering', 'ML', 'Gaming'],
  },
  {
    id: 'byteweb-cam-4k',
    name: 'ByteCam 4K',
    slug: 'bytecam-4k',
    category: 'DEV_BOARD',
    brand: 'ByteCam',
    price: 18999,
    image: '/build-lab/bytecam-4k.svg',
    summary: '4K webcam with autofocus for remote demos and meetings.',
    capabilities: {
      ports: ['USB_C'],
      operatingSystems: ['macOS', 'Windows', 'Linux'],
      compatibilityTags: ['camera', 'video-call'],
      workloadTags: ['meetings', 'streaming'],
      dimensionsMm: { width: 100, depth: 50, height: 50 },
    },
    tags: ['webcam', '4k', 'meetings'],
    scoreWeight: 74,
    recommendedFor: ['Meetings', 'Streaming'],
  },
  {
    id: 'bytepower-140w',
    name: 'BytePower 140W',
    slug: 'bytepower-140w',
    category: 'POWER',
    brand: 'BytePower',
    price: 6999,
    image: '/build-lab/bytepower-140w.svg',
    summary: 'GaN charger for high-wattage laptops and peripherals.',
    capabilities: {
      ports: ['USB_C', 'USB_A'],
      powerOutputW: 140,
      compatibilityTags: ['pd', 'charger'],
      workloadTags: ['charging'],
      dimensionsMm: { width: 75, depth: 65, height: 30 },
    },
    tags: ['power', 'charger', 'gan'],
    scoreWeight: 85,
    recommendedFor: ['High-power laptops'],
  },
  {
    id: 'bytecable-usbc-hdmi',
    name: 'ByteCable USB-C to HDMI',
    slug: 'bytecable-usbc-hdmi',
    category: 'CABLE',
    brand: 'ByteCable',
    price: 1999,
    image: '/build-lab/bytecable-usbc-hdmi.svg',
    summary: 'Reliable cable for display output from compatible USB-C devices.',
    capabilities: {
      ports: ['USB_C', 'HDMI'],
      bandwidthGbps: 18,
      compatibilityTags: ['cable', 'display'],
      dimensionsMm: { width: 1, depth: 1, height: 1 },
    },
    tags: ['cable', 'display', 'adapter'],
    scoreWeight: 68,
    recommendedFor: ['Display extension'],
  },
  {
    id: 'bytenet-wifi-7',
    name: 'ByteNet Wi-Fi 7 Adapter',
    slug: 'bytenet-wifi-7-adapter',
    category: 'NETWORKING',
    brand: 'ByteNet',
    price: 7999,
    image: '/build-lab/bytenet-wifi-7-adapter.svg',
    summary: 'Fast wireless adapter for modern desks and backup networking.',
    capabilities: {
      ports: ['USB_C'],
      networkStandards: ['Wi-Fi 7', 'Bluetooth 5.4'],
      compatibilityTags: ['networking', 'wireless'],
      workloadTags: ['connectivity'],
      dimensionsMm: { width: 95, depth: 25, height: 10 },
    },
    tags: ['networking', 'wifi', 'adapter'],
    scoreWeight: 70,
    recommendedFor: ['Portable desks', 'Backup network'],
  },
  {
    id: 'byteboard-dev-kit',
    name: 'ByteBoard Dev Kit',
    slug: 'byteboard-dev-kit',
    category: 'DEV_BOARD',
    brand: 'ByteBoard',
    price: 9999,
    image: '/build-lab/byteboard-dev-kit.svg',
    summary: 'Compact dev board for prototyping, automation, and IoT projects.',
    capabilities: {
      ports: ['USB_C', 'USB_A'],
      operatingSystems: ['macOS', 'Windows', 'Linux'],
      compatibilityTags: ['dev-board', 'prototype'],
      workloadTags: ['iot', 'automation'],
      dimensionsMm: { width: 85, depth: 55, height: 15 },
    },
    tags: ['dev-board', 'iot', 'prototype'],
    scoreWeight: 66,
    recommendedFor: ['Prototyping', 'Automation'],
  },
];

export const catalogFilters = {
  categories: ['LAPTOP', 'DESKTOP', 'MONITOR', 'GPU', 'DOCK', 'KEYBOARD', 'MOUSE', 'STORAGE', 'NETWORKING', 'POWER', 'CABLE', 'DEV_BOARD'],
  connectors: ['USB_C', 'THUNDERBOLT_4', 'HDMI', 'DISPLAYPORT', 'PCIe', 'ETHERNET'],
};
